project:
  name: Surn-Test
  author: John


# The target language config
target:
  # The name of the language to compile to
  name: php
  version: 8.0.0

  # To compile to a binary directly use this config:
  # name: llvm
  # version: 13.0.0